// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Author struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	Country string `json:"country"`
}

type Book struct {
	ID     string  `json:"id"`
	Code   string  `json:"code"`
	Title  string  `json:"title"`
	Author *Author `json:"author"`
}

type NewBook struct {
	Code          string `json:"code"`
	Title         string `json:"title"`
	AuthorName    string `json:"authorName"`
	AuthorCountry string `json:"authorCountry"`
}
